---
# tasks file for mongodb
- name: Add mongodb.org gpgkey
  ansible.builtin.apt_key:
    url: https://www.mongodb.org/static/pgp/server-7.0.asc
    state: present
  retries: 5

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse
    state: present

- name: Install MongoDB Packages
  package:
    name: "mongodb-org"
    state: present
  register: _pkg
  until: _pkg is succeeded
  retries: 5

- name: Start mongod service
  service:
    name: "{{ mongod_service }}"
    state: started
    enabled: yes

#- name: Install pymongo python3 library
#  pip:
#    name: pymongo
#    executable: pip3
    
#- name: Install pymongo library
#  pip:
#    name: pymongo
#    version: 3.12.3
#    executable: pip

#- name: Create MongoDB root user
#  mongodb_user:
#    login_port: "27017"
#    database: "admin"
#    name: "{{ mongodb_admin_user }}"
#    password: "{{ mongodb_admin_password }}"
#    roles: "root"

#- name: Copy config file
#  template:
#    src: "mongod.conf.j2"
#    dest: /etc/mongod.conf
#    owner: "{{ mongodb_user }}"
#    group: "{{ mongodb_group }}"
#  notify:
#    - Restart mongod service
