---
- hosts: all
  gather_facts: true

  tasks:
  - name: Install Python Pip
    package:
      name: python3-pip
      state: present

  - name: Install Python3
    package:
      name: python3
      state: present

- name: Install specified python requirements and custom Index URL
  ansible.builtin.pip:
    name:
      - torch
      - torchvision
      - torchaudio
    extra_args: -i https://download.pytorch.org/whl/cpu
